[package]
name = "image-merger"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "A tool to merge multiple images into one."
repository = "https://github.com/NextChai/image-merger"

[profile.release]
codegen-units = 1
lto = false


[dependencies]
image = "0.24.7"
rayon = "1.8.0"
