[package]
name = "image-merger"
version = "0.0.1"
edition = "2021"


[dependencies]
bytes = "1.4.0"
image = "0.24.7"
anyhow = "1.0.71"
memmap = "0.7.0"
num-traits = "0.2.15"
rayon = "1.8.0"
sync-unsafe-cell = "0.1.1"